### ISSUE TITLE
Flex Layout doesn't respect active/inactive Game Objects

### ISSUE THREAD

**Issue by iMobCoding** [gilzoide/unity-flex-ui#19] opened 2024-04-08 15:07 UTC
Flex Layout shouldn't consider Game Objects that are inactive in the Hierarchy. Instead it lays out everything like those objects are active. Even if I disable Flex Layout component on inactive objects it doesn't do anything...

**Comment by gilzoide** [comment] 2024-04-21 21:17
Seems like a duplicate of #18.

**Closed** 2024-04-27 17:52 UTC
Labels: bug, duplicate
